### ISSUE TITLE
Migrate away from componentWillMount

### ISSUE THREAD

**Issue by heikkilamarko** [mobxjs/mobx-react#447]
The latest React discourages using `componentWillMount`.
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by mweststrate** [comment]
Additional notes https://github.com/facebook/react/tree/master/packages/create-subscription

**Comment by lucsky** [comment]
Incidentally, using the new `<React.StrictMode>` (https://reactjs.org/docs/strict-mode.html) around observer components triggers lifecycle warnings.

**Comment by evoyy** [comment]
This is preventing MobX users from migrating to React's new component APIs. I tried to migrate from ````componentWillReceiveProps()```` to the new static method ````getDerivedStateFromProps()```` and I receive the following warning:

````
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

NavBar uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
````

**Comment by malash** [comment]
I give a advice that the alternative of `componentWillMount` could be the first function call of `render` in React new lifecycles. 

I have tried it in the Noflux React binding in this pr https://github.com/nofluxjs/noflux-react/pull/24 and it works.

**Comment by dw2** [comment]
MobX user here, checking in to confirm that this is preventing us from using getDerivedStateFromProps :(

**Comment by luisherranz** [comment]
Which one of these approaches do you think is better?
- Move the logic of the current `componentWillMount` to the `constructor`.
- Move the logic of the current `componentWillMount` to the `render` and use a flag to only execute it the first time.

**Comment by xcv58** [comment]
Is it possible to use `componentDidMount`? @luisherranz

**Comment by luisherranz** [comment]
I don't think so because it looks like it is generating a function to do the first render.

**Comment by aripekkako** [comment]
The hard thing here is that the old `React.createClass` syntax (that is used in this packages tests) does no play well without `componentWIllMount` (cf. https://github.com/facebook/react/issues/7671) as it does not support a `constructor`. I tried to see, if I could replace the `componentWillMount` in the `reactiveMixin` with a constructor method and realized that it likely will not work when `React.createClass` is used. Should it be replaced with a combination of `getInitialState` (for `React.createClass`) and `constructor`?

**Comment by luisherranz** [comment]
There is an official FB package to polyfill the new components:
https://github.com/reactjs/react-lifecycles-compat
Could that help in this case?

**Comment by aripekkako** [comment]
Would lovet to test, however we have to support IE11, so we're stuck with Mobx 4. Do you think that the React 16.3 support will be backported to Mobx 4 also?

**Comment by mweststrate** [comment]
@aripekkako it is unrelated, mobx-react works fine with MobX 4 :) (mobx and mobx-react version numbers are independent although close, so this is unrelated to the mobx 5 changes)

**Comment by le0nik** [comment]
@orballo looks like mobx-react just bundles all dependencies at build-time(which is not a good practice in my opinion), so `hoist-non-react-statics` is not up-to-date and does not exclude `getDerivedStateFromProps`. You can see it by searching for `REACT_STATICS ` here https://unpkg.com/mobx-react@5.1.0-rc.1/index.js and comparing it to the latest version of `hoist-non-react-statics` here https://github.com/mridgway/hoist-non-react-statics/blob/v2.5.0/index.js#L18

**Comment by mweststrate** [comment]
Should be fixed by: mobx-react@5.1.0-rc.2

**Comment by luisherranz** [comment]
@mweststrate `getDerivedStateFromProps ` is working perfectly now 👏 
https://codesandbox.io/s/8876249yll

**Comment by le0nik** [comment]
@mweststrate looks like build still has an old version of `hoist-non-react-statics`.

If you search for `REACT_STATICS` [here](https://unpkg.com/mobx-react@5.1.0-rc.2/index.js) you won't find `getDerivedStateFromProps` key inside it.

Codesandbox example above also doesn't work with `mobx-react@5.1.0-rc.2` for me.

Or am I the only one with this problem?

**Comment by luisherranz** [comment]
> Codesandbox example above also doesn't work with mobx-react@5.1.0-rc.2 for me.

@le0nik do you mean my codesandbox (https://codesandbox.io/s/8876249yll)? What part is not working for you?

**Comment by aripekkako** [comment]
I can comfirm we still get `Warning: inject-ComponentXYZ-with-configStore: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.` with `rc.2`.

**Comment by mweststrate** [comment]
@aripekkako test case?

Op ma 30 apr. 2018 13:41 schreef aripekkako <notifications@github.com>:

**Comment by aripekkako** [comment]
Sorry, took me a while. I think that CodeSandbox does not show these warnings, but here (https://codesandbox.io/s/ywmx8oj4o1) is code where you can see that `getDerivedStateFromProps` gets called before the `constructor` if inject is used and if you don't use it `constructor` is called first.

```
import React, { Component } from "react";
import { render } from "react-dom";
import { Provider, inject, observer } from "mobx-react";

@observer
class Main extends Component {
  state = {
    activePropertyElementMap: {}
  };

  constructor(props) {
    console.log("CONSTRUCTOR");
    super(props);
  }

  static getDerivedStateFromProps(nextProps, prevState) {
    console.log("PREVSTATE");
    return null;
  }

  render() {
    const { data, store} = this.props;
    return (
      <div>Test-content</div>
    );
  }
}
// This results in:
//PREVSTATE
//CONSTRUCTOR
//PREVSTATE
let MainInjected = inject('store')(Main);
// Uncomment the following line to see default behaviour (without inject)
//CONSTRUCTOR
//PREVSTATE
//MainInjected = Main;


const store = {};

const App = () => (
  <Provider store={store}>
    <MainInjected data={'abc'} />
  </Provider>
);

render(<App />, document.getElementById("root"));
```

**Comment by luisherranz** [comment]
@le0nik that error was not related to `mobx-react` but with the `getDerivedStateFromProps` function itself. It looks like `prevState` is `null` on the first call even if you defined a `state` prop.

Check my codesanbox for the updated code: https://codesandbox.io/s/8876249yll

**Comment by le0nik** [comment]
@luisherranz in this example https://codesandbox.io/s/rl3rk7jk34 if you remove replace `<MainInjected />` with `<Main />` you'll see `prevState` in console is an object, not `null`.

**Comment by luisherranz** [comment]
I see. I was playing with @aripekkako codesandbox and I found out that the `getDerivedStateFromProps` gets called twice, once for the injected-component and once for the component itself:
https://codesandbox.io/s/2p6pkw8vry

**Comment by le0nik** [comment]
correct. That's because an older version of `hoist-non-react-statics` is bundled into `mobx-react` and it copies `getDerivedStateFromProps` onto `Inject` HoC component, when it shouldn't(and latest version doesn't do that).

**Comment by mweststrate** [comment]
Please make sure to base the testing on -rc.2 :)

Op ma 30 apr. 2018 om 15:35 schreef Leonid Nikiforenko <
notifications@github.com>:

**Comment by luisherranz** [comment]
@mweststrate this is on rc.2 and if you take a look at the console you can see the `getDerivedStateFromProps` executed twice, once for the injected component and once for the component itself:
https://codesandbox.io/s/2p6pkw8vry

**Comment by le0nik** [comment]
@mweststrate it's on `rc.2`

**Comment by mweststrate** [comment]
Interestingly, if I copy the above test case to jest, the problem disappears :-/

**Comment by mweststrate** [comment]
Ok, I'm a noob, forgot to build before publish, `rc.3` should fix it :)

**Comment by mweststrate** [comment]
https://codesandbox.io/s/o495z6kvvq

**Comment by mweststrate** [comment]
Released the changes as `mobx-react@5.1.0`, it fully supports React 16.3 now, and also deprecated some bad usage patterns.
